name: Push to Public Repo

on:
  push:
    branches: ["main"]  
  workflow_dispatch:     

jobs:
  deploy-to-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.###}} (zamiast ### wpisujesz nazwę tokenu)
        with:

          source-directory: 'Folder z prywatnego' 

          destination-github-username: 'Login'

          destination-repository-name: 'Repozytorium publiczny'

          user-email: Mail
          target-branch: main
