name: Push to Public Repo

on:
  push:
    branches: ["main"]  
  workflow_dispatch:     

jobs:
  deploy-to-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_TOKEN }}
        with:

          source-directory: 'zad3_css' 

          destination-github-username: '76144'

          destination-repository-name: 'cv1_76144'

          user-email: kpietra5@stu.vistula.edu.pl
          target-branch: main
